import { describe, expect, it } from "vitest";
import {
  ApiError, cleanText, createApiClient, formatDateTime, formatIban, formatMoney, isValidIban, normalizePhone,
  parseMoneyInput, passwordIssue, pinIssue, registerSchema, transferSchema, uuid,
} from "../src";

// Vector generated by the backend (BfaNet.Application.Common.Iban.Generate).
const GOOD_IBAN = "AO06000600011000000000193";

describe("iban", () => {
  it("accepts backend-generated IBANs", () => {
    expect(isValidIban(GOOD_IBAN)).toBe(true);
    expect(isValidIban("AO06 0006 0001 1000 0000 0019 3")).toBe(true);
  });
  it("rejects wrong checksum / format", () => {
    expect(isValidIban("AO06000600011000000000194")).toBe(false);
    expect(isValidIban("PT50000201231234567890154")).toBe(false);
    expect(isValidIban("")).toBe(false);
  });
  it("formats in groups of 4", () => expect(formatIban(GOOD_IBAN)).toBe("AO06 0006 0001 1000 0000 0019 3"));
});

describe("credentials (parity with CredentialPolicy on the server)", () => {
  it.each([
    ["Curta1!", false], ["semmaiusculas1!", false], ["SEMMINUSCULAS1!", false], ["SemNumeros!!ab", false],
    ["SemSimbolos123ab", false], ["Xaaabcdefg1!", false], ["Boa#Passe-2026x", true],
  ])("password %s -> ok=%s", (pwd, ok) => expect(passwordIssue(pwd) === null).toBe(ok));

  it("rejects passwords containing the name", () =>
    expect(passwordIssue("Maria#2026xyz", { fullName: "Maria Santos" })).not.toBeNull());

  it.each([["123456", false], ["654321", false], ["111111", false], ["12345", false], ["12a456", false], ["482915", true]])(
    "pin %s -> ok=%s", (pin, ok) => expect(pinIssue(pin) === null).toBe(ok));
});

describe("sanitisation", () => {
  it("strips bidi overrides, zero-width and control characters", () =>
    expect(cleanText("Pago‮ a​ Jo\u0000ao")).toBe("Pago a Joao"));
  it("collapses whitespace", () => expect(cleanText("  a \t\n b   c ")).toBe("a b c"));
  it("normalises phones", () => {
    expect(normalizePhone("+244 923 456 789")).toBe("923456789");
    expect(normalizePhone("923-456-789")).toBe("923456789");
  });
});

describe("money", () => {
  it("parses only unambiguous input", () => {
    expect(parseMoneyInput("1500")).toBe(1500);
    expect(parseMoneyInput("1 500,50")).toBe(1500.5);
    expect(parseMoneyInput("10.5")).toBe(10.5);
    expect(parseMoneyInput("1.500")).toBeNaN();
    expect(parseMoneyInput("10,123")).toBeNaN();
    expect(parseMoneyInput("abc")).toBeNaN();
    expect(parseMoneyInput("-5")).toBeNaN();
  });
  it("formats with nbsp grouping and comma decimals", () => {
    expect(formatMoney(1250000.5)).toBe("1 250 000,50 Kz");
    expect(formatMoney(-25, "AOA")).toBe("-25,00 Kz");
  });
  it("formats dates in Luanda time (UTC+1)", () => expect(formatDateTime("2026-09-21T12:03:00Z")).toBe("21 Set 2026, 13:03"));
});

describe("schemas", () => {
  const base = { fromAccountId: "01a0c3d8-7ddd-747d-947e-e8caf2efb50d", toIban: GOOD_IBAN, beneficiaryName: "", amount: "25 000,50", description: "Renda" };

  it("transfer: sanitises and converts", () => {
    const r = transferSchema.parse({ ...base, toIban: "ao06 0006 0001 1000 0000 0019 3", description: "  Renda​  " });
    expect(r.toIban).toBe(GOOD_IBAN);
    expect(r.amount).toBe(25000.5);
    expect(r.description).toBe("Renda");
  });
  it("transfer: rejects markup, bad amounts, bad iban", () => {
    expect(transferSchema.safeParse({ ...base, description: "<img src=x onerror=alert(1)>" }).success).toBe(false);
    expect(transferSchema.safeParse({ ...base, amount: "0" }).success).toBe(false);
    expect(transferSchema.safeParse({ ...base, amount: "6 000 000" }).success).toBe(false);
    expect(transferSchema.safeParse({ ...base, toIban: "AO06000600011000000000194" }).success).toBe(false);
  });
  it("transfer: interbank requires beneficiary name", () => {
    const other = "AO06004000010000000001279";
    expect(transferSchema.safeParse({ ...base, toIban: other }).success).toBe(false);
    expect(transferSchema.safeParse({ ...base, toIban: other, beneficiaryName: "Ana Costa" }).success).toBe(true);
  });
  it("register: mismatches, minors and terms are reported per field", () => {
    const r = registerSchema.safeParse({
      fullName: "Ana Maria", email: "ana@example.ao", phone: "923456789", nationalId: "005678901LA041", taxId: "",
      birthDate: `${new Date().getUTCFullYear() - 10}-01-01`, password: "Boa#Passe-2026x", confirmPassword: "outra",
      pin: "482915", confirmPin: "482915", acceptTerms: false,
    });
    expect(r.success).toBe(false);
    const fields = new Set(r.error!.issues.map((i) => i.path[0]));
    expect(fields).toContain("birthDate");
    expect(fields).toContain("confirmPassword");
    expect(fields).toContain("acceptTerms");
  });
});

describe("api client", () => {
  const json = (status: number, body?: unknown) => new Response(body === undefined ? null : JSON.stringify(body), { status });

  it("maps problem+json to ApiError with field errors", async () => {
    const api = createApiClient({ baseUrl: "", clientKind: "web", fetchImpl: async () => json(422, { status: 422, code: "validation_error", title: "Dados inválidos.", errors: { iban: ["IBAN inválido."] } }) });
    const err = (await api.post("/x", { body: {} }).catch((e) => e)) as ApiError;
    expect(err.fieldErrors!.iban).toEqual(["IBAN inválido."]);
  });

  it("refreshes once for parallel 401s and retries", async () => {
    let fresh = false, refreshes = 0;
    const fetchImpl = async () => (fresh ? json(200, { ok: true }) : json(401, { code: "unauthorized", title: "x" }));
    const api = createApiClient({
      baseUrl: "", clientKind: "web", fetchImpl,
      refresh: async () => { refreshes++; await new Promise((r) => setTimeout(r, 10)); fresh = true; return true; },
    });
    const results = await Promise.all([api.get("/a"), api.get("/b"), api.get("/c")]);
    expect(results).toEqual([{ ok: true }, { ok: true }, { ok: true }]);
    expect(refreshes).toBe(1);
  });

  it("signals expiry when refresh fails and does not loop", async () => {
    let expired = 0;
    const api = createApiClient({ baseUrl: "", clientKind: "web", fetchImpl: async () => json(401, { code: "unauthorized", title: "x" }), refresh: async () => false, onSessionExpired: () => expired++ });
    await expect(api.get("/a")).rejects.toMatchObject({ status: 401 });
    expect(expired).toBe(1);
  });

  it("network failures become status 0", async () => {
    const api = createApiClient({ baseUrl: "", clientKind: "web", fetchImpl: async () => { throw new TypeError("fail"); } });
    await expect(api.get("/a")).rejects.toMatchObject({ status: 0, code: "network_error" });
  });

  it("sends client header, bearer and idempotency key", async () => {
    let seen: Record<string, string> = {};
    const api = createApiClient({ baseUrl: "http://x", clientKind: "mobile", getAccessToken: () => "tok", fetchImpl: async (_u, init) => { seen = init!.headers as Record<string, string>; return json(200, {}); } });
    await api.post("/p", { body: {}, idempotencyKey: "k1" });
    expect(seen).toMatchObject({ "X-BFA-Client": "mobile", Authorization: "Bearer tok", "Idempotency-Key": "k1" });
  });
});

it("uuid v4 shape", () => expect(uuid()).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/));

import { buildKwikQr, buildPayQr, parseQr, rechargeSchema, statePaymentSchema, kwikSchema, RECHARGE_PROVIDERS } from "../src";

describe("recharge / state / kwik schemas", () => {
  const acc = "01a0c3d8-7ddd-747d-947e-e8caf2efb50d";
  it("recharge validates the identifier per provider", () => {
    expect(rechargeSchema.safeParse({ fromAccountId: acc, provider: "Unitel", identifier: "+244 923 456 789", amount: "500" }).success).toBe(true);
    expect(rechargeSchema.safeParse({ fromAccountId: acc, provider: "Unitel", identifier: "12345", amount: "500" }).success).toBe(false);
    expect(rechargeSchema.safeParse({ fromAccountId: acc, provider: "Dstv", identifier: "1234567890", amount: "15000" }).success).toBe(true);
    expect(rechargeSchema.safeParse({ fromAccountId: acc, provider: "Ende", identifier: "12345", amount: "500" }).success).toBe(false);
    expect(rechargeSchema.safeParse({ fromAccountId: acc, provider: "Ende", identifier: "12345abc9012", amount: "500" }).success).toBe(false);
  });
  it("recharge enforces the provider's amount range", () => {
    expect(rechargeSchema.safeParse({ fromAccountId: acc, provider: "Unitel", identifier: "923456789", amount: "60000" }).success).toBe(false);
    expect(rechargeSchema.safeParse({ fromAccountId: acc, provider: "Dstv", identifier: "1234567890", amount: "60000" }).success).toBe(true);
    expect(RECHARGE_PROVIDERS.Unitel.max).toBe(50_000);
  });
  it("state payment needs exactly 13 digits", () => {
    expect(statePaymentSchema.safeParse({ fromAccountId: acc, reference: "1234567890123", amount: "1000" }).success).toBe(true);
    expect(statePaymentSchema.safeParse({ fromAccountId: acc, reference: "123 456 789 0123", amount: "1000" }).success).toBe(true);
    expect(statePaymentSchema.safeParse({ fromAccountId: acc, reference: "123456789012", amount: "1000" }).success).toBe(false);
    expect(statePaymentSchema.safeParse({ fromAccountId: acc, reference: "12345678901ab", amount: "1000" }).success).toBe(false);
  });
  it("kwik key is a normalised mobile number", () => {
    const r = kwikSchema.parse({ fromAccountId: acc, key: "+244 923 456 789", amount: "100", description: "" });
    expect(r.key).toBe("923456789");
    expect(kwikSchema.safeParse({ fromAccountId: acc, key: "823456789", amount: "100", description: "" }).success).toBe(false);
  });
});

describe("qr parser", () => {
  const iban = "AO06000600011000000000193";
  it("parses a valid payment QR and normalises it", () => {
    const r = parseQr(`BFAPAY:v1;iban=${iban};amount=1500.50;name=Loja  Central;ref=FT-2026/19`);
    expect(r).toEqual({ ok: true, payload: { kind: "pay", iban, amount: 1500.5, name: "Loja Central", ref: "FT-2026/19" } });
  });
  it("parses a KWiK QR", () => {
    expect(parseQr("BFAKWIK:v1;key=+244 923 456 789;amount=200")).toEqual({ ok: true, payload: { kind: "kwik", key: "923456789", amount: 200, name: undefined } });
  });
  it("round-trips through the builders", () => {
    expect(parseQr(buildPayQr({ iban, amount: 10, name: "Ana" })).ok).toBe(true);
    expect(parseQr(buildKwikQr({ key: "923456789" })).ok).toBe(true);
  });
  it.each([
    ["", "empty"], ["https://evil.example/pay", "foreign scheme"], ["BFAPAY:v2;iban=" + iban, "wrong version"],
    ["BFAPAY:v1;iban=AO06000600011000000000194", "bad checksum"], [`BFAPAY:v1;iban=${iban};amount=-5`, "negative"],
    [`BFAPAY:v1;iban=${iban};amount=0`, "zero"], [`BFAPAY:v1;iban=${iban};amount=1.234`, "3 decimals"],
    [`BFAPAY:v1;iban=${iban};evil=1`, "unknown key"], [`BFAPAY:v1;iban=${iban};iban=${iban}`, "duplicate key"],
    [`BFAPAY:v1;iban=${iban};name=<script>alert(1)</script>`, "markup in name"], [`BFAPAY:v1;iban=${iban};ref=a b`, "bad ref"],
    ["BFAKWIK:v1;key=12345", "bad key"], ["BFAPAY:v1;" + "a=b;".repeat(100), "too long"],
  ])("rejects %s (%s)", (raw) => expect(parseQr(raw).ok).toBe(false));
});

import { dateRangeSchema, luandaToday, presetRange, shiftDays } from "../src";

describe("periods", () => {
  it("uses Luanda time (UTC+1) for 'today'", () => {
    expect(luandaToday(new Date("2026-09-21T23:30:00Z"))).toBe("2026-09-22");
    expect(luandaToday(new Date("2026-09-21T12:00:00Z"))).toBe("2026-09-21");
  });
  it("computes presets", () => {
    const now = new Date("2026-09-21T12:00:00Z");
    expect(presetRange("month", now)).toEqual({ from: "2026-09-01", to: "2026-09-21" });
    expect(presetRange("30d", now)).toEqual({ from: "2026-08-23", to: "2026-09-21" });
    expect(shiftDays("2026-03-01", -1)).toBe("2026-02-28");
  });
  it("validates custom ranges", () => {
    expect(dateRangeSchema.safeParse({ from: "2026-01-01", to: "2026-02-01" }).success).toBe(true);
    expect(dateRangeSchema.safeParse({ from: "2026-02-01", to: "2026-01-01" }).success).toBe(false);
    expect(dateRangeSchema.safeParse({ from: "2026-02-30", to: "2026-03-01" }).success).toBe(false);
    expect(dateRangeSchema.safeParse({ from: "2024-01-01", to: "2026-01-01" }).success).toBe(false); // > 366 days
    expect(dateRangeSchema.safeParse({ from: "2026-01-01", to: "2999-01-01" }).success).toBe(false);
    expect(dateRangeSchema.safeParse({ from: "01/01/2026", to: "2026-01-02" }).success).toBe(false);
  });
});

describe("api client: raw bodies", () => {
  it("sends FormData without a Content-Type so fetch can set the multipart boundary", async () => {
    let seen: { headers: Record<string, string>; body: unknown } | null = null;
    const api = createApiClient({ baseUrl: "", clientKind: "web", fetchImpl: async (_u, init) => { seen = { headers: init!.headers as Record<string, string>, body: init!.body }; return new Response(null, { status: 204 }); } });
    const form = new FormData(); form.append("file", new Blob(["x"], { type: "image/png" }), "a.png");
    await api.put("/x", { raw: { data: form } });
    expect(seen!.body).toBe(form);
    expect(seen!.headers["Content-Type"]).toBeUndefined();
  });
});

import { receiptPdfPath, statementPdfPath } from "../src";

describe("pdf paths", () => {
  it("builds receipt and statement URLs", () => {
    expect(receiptPdfPath("abc")).toBe("/api/v1/transactions/abc/receipt.pdf");
    expect(statementPdfPath("acc")).toBe("/api/v1/accounts/acc/statement.pdf");
    expect(statementPdfPath("acc", { from: "2026-09-01", to: "2026-09-21" })).toBe("/api/v1/accounts/acc/statement.pdf?from=2026-09-01&to=2026-09-21");
  });
  it("encodes path segments", () => expect(receiptPdfPath("a/b")).toBe("/api/v1/transactions/a%2Fb/receipt.pdf"));
});

import { makeCreditSchema, monthShort } from "../src";

describe("credit schema", () => {
  const schema = makeCreditSchema({ minAmount: 20_000, maxAmount: 400_000, terms: [3, 6, 9, 12] });
  const acc = "01a0c3d8-7ddd-747d-947e-e8caf2efb50d";
  it("accepts amounts and terms inside the offer", () => expect(schema.safeParse({ accountId: acc, amount: "150 000", months: 6 }).success).toBe(true));
  it("rejects outside the offer", () => {
    expect(schema.safeParse({ accountId: acc, amount: "10 000", months: 6 }).success).toBe(false);
    expect(schema.safeParse({ accountId: acc, amount: "500 000", months: 6 }).success).toBe(false);
    expect(schema.safeParse({ accountId: acc, amount: "100 000", months: 5 }).success).toBe(false);
  });
  it("labels months", () => expect(monthShort("2026-09")).toBe("Set"));
});
